### ISSUE TITLE
Error on test

### ISSUE THREAD

**Issue by joaomello-zz** [psantosl/p2pcopy#3]
I tried to use, to make a test... but received this error "The underlying connection was closed: An unexpected error occurred on a send.", what could be wrong?

**Comment by joaomello-zz** [comment]
That's because of this https://github.com/psantosl/p2pcopy/blob/master/InternetTime.cs#L23
I changed to another server:
```C#
var client = new TcpClient("time.nist.gov", 13);
using (var streamReader = new StreamReader(client.GetStream()))
{
    var response = streamReader.ReadToEnd();
    var utcDateTimeString = response.Substring(7, 17);
    var localDateTime = DateTime.ParseExact(utcDateTimeString, "yy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal);
}
```

**Comment by joaomello-zz** [comment]
I'm getting this error `Error connecting to xx.xxx.xxx.xx:1033 Connection setup failure: connection time out. UDT Error Code: 1001`

**Comment by psantosl** [comment]
Hi Joao,

I can't tell you much about "an unexpected error occurred" :-) Not enough info as you might understand.

The time server: ok, you can change it to a different one.

Connection timed out: looks like it can't actually connect.

I mean, how p2p works is:
* Both parties try to open a connection to the other peer at the same time, trying to open a hole.
* Most of the times it works, but ... it is not guaranteed to happen.

**Comment by knocte** [comment]
> That's because of this https://github.com/psantosl/p2pcopy/blob/master/InternetTime.cs#L23
> I changed to another server:

I think this has been fixed in https://github.com/psantosl/p2pcopy/commit/4c1256156c00a8a679a7a18e8328c98769ac6e79 , can you close?
